server:
  port: 9090

spring:
  application:
    name: springboot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '123456'
    url: jdbc:mysql://localhost:3306/xm-pro?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true

mybatis:
  # 映射xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 配置日誌 (注意：這兩行必須縮排在 configuration 底下)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 把數據庫的下劃線改成駝峰 (注意：末尾絕對不能有分號 ;)
    map-underscore-to-camel-case: true